### ISSUE TITLE
Suggestion: overlay option for cookie modal

### ISSUE THREAD

**Issue by takashi1kun** [rlankhorst/complianz-gdpr#160]
It would be great if you add an option to add a overlay and block scroll whit the cookie modal/banner until they accept the cookies, i mean, the thing that shadows the rest of the page and do not let you interact whit the rest of the page.
That would be better for compliance whit the GDPR

**Comment by rlankhorst** [comment]
Hi @takashi1kun, 

Thanks for your suggestion. But: for the GDPR, a full Cookie Wall is not allowed:
https://complianz.io/cookie-walls-allowed-or-not-gdpr/

There is an alternative: a "soft cookie wall", which is on our to do list. A soft cookie wall has the look of a cookie wall, but can be dismissed. Let me know if you have any questions!
