### ISSUE TITLE
Theme template file override not working 

### ISSUE THREAD

**Issue by xantek-imc** [rlankhorst/complianz-gdpr#242]
Greetings,

It looks  cmplz_get_template has a bug when creating the $theme_file variable.  I discovered this issue during local development on Windows but it looks like it would impact *nix as well.

https://github.com/rlankhorst/complianz-gdpr/blob/2d02a2add57499a7d68e95e940d45081323a974c/functions.php#L38-L40

Creating a PR

**Comment by rlankhorst** [comment]
@xantek-imc thanks, has been merged.

**Comment by rlankhorst** [comment]
@xantek-imc if you have a wordpress username I can add you as contributor

**Comment by xantek-imc** [comment]
@rlankhorst profiles.wordpress.org username: xantek
