### ISSUE TITLE
`<iframe>` are not detected when they stand on multiple lines

### ISSUE THREAD

**Issue by pierrotevrard-idp** [rlankhorst/complianz-gdpr#244]
I've found this issue with a custom gutenberg block rendering something like:

```
<iframe
   style="position: absolute; left: 0; top: 0; width: 100%; height: 100%;"
  width="1680"
  height="945"
  src="https://www.youtube.com/embed/{{ block.youtube_video_id }}"
  frameborder="0"
  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
```

In that case, the regular expression `'/<(iframe)[^>]*src=[\'"](http:\/\/|https:\/\/|\/\/)' . $url_pattern . '[\'"].*?>.*?<\/iframe>/i'` won't work until `s` modifier is set (dot all ; see class-cookie-blocker.php, line 257).

**Comment by rlankhorst** [comment]
@pierrotevrard-idp thanks, it's been merged!

**Comment by rlankhorst** [comment]
@pierrotevrard-idp if you have a wordpress username I can add you as contributor

**Comment by pierrotevrard-idp** [comment]
Yes! https://profiles.wordpress.org/pierrotevrard/
Thanks ^^
