### ISSUE TITLE
`<iframe data-src-cmplz` replacement failure

### ISSUE THREAD

**Issue by pierrotevrard-idp** [rlankhorst/complianz-gdpr#246]
I've found this issue with a custom gutenberg block rendering something like (like #244):

```
<iframe
   style="position: absolute; left: 0; top: 0; width: 100%; height: 100%;"
  width="1680"
  height="945"
  src="https://www.youtube.com/embed/{{ block.youtube_video_id }}"
  frameborder="0"
  allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
```

In that case, the replacement of "<iframe " won't work because there is no space after the opening `<iframe>` tag (it is a new line ; see class-cookie-blocker.php, line 265).

**Comment by rlankhorst** [comment]
@pierrotevrard-idp thanks, we'll test your solution :)
