### ISSUE TITLE
jQuery compatibility

### ISSUE THREAD

**Issue by pierrotevrard-idp** [rlankhorst/complianz-gdpr#247]
As mentionned here: https://stackoverflow.com/questions/5788499/jquery-iframe-load-event, we're supposed to use `$('selector').on('load',function(){});` instead of `$('selector').load( function(){} );`

Issue stands at line 228 of `assets/js/cookieconfig.js`

**Comment by rlankhorst** [comment]
@pierrotevrard-idp thanks for your input! We'll test this and merg when successful.

**Comment by rlankhorst** [comment]
@pierrotevrard-idp when I try this on a youtube video, the video seems to load twice. First the placeholder is replaced with the video, the it seems to "flash" and load load again. Not sure why this happens. 

Currently the video is loaded in the background, then, when it's loaded, the placeholder fades out. This results in a very smooth transition. The proposal is not as smooth.

**Comment by pierrotevrard-idp** [comment]
I didn't notice the smooth effect. My issue is with a custom jQuery library, so it's ok. I just gonna close this request.

Thanks
