### ISSUE TITLE
`cookieFunction` and `collectedPersonalData` sync across different languages

### ISSUE THREAD

**Issue by pierrotevrard-idp** [rlankhorst/complianz-gdpr#259]
I think that it is an error because multilanguages feature should be enable only on PRO version, but on FREE version (since 4.3.6), I got the select box for languages above the list of cookies.

![image](https://user-images.githubusercontent.com/57230131/78364570-f4875500-75bd-11ea-8513-8e960a50f802.png)

I'm using WordPress 5.3.2, Complianz GDPR 4.4.1 and Polylang 2.6.10.

Also, the select box is not functionnal (probably because it's the FREE version) and leads to a logic where all cookies with the same name are updated at the same time.

Thanks

**Comment by rlankhorst** [comment]
Hi @pierrotevrard-idp, 

This is not a pro feature, but is available in free. I don't recognize what you describe: I have two languages on my test setup, and get the cookies back in two languages after the sync. If you added a second language after your sync, you may need to run the cookie scan again to get them in the other languages as well.

If this is not the issue, I would need to see it live to be able to find the problem.

**Comment by pierrotevrard-idp** [comment]
Ok, it's a bit difficult to reproduce, but following these steps, it should:

- 2 languages EN, FR
- sucessful scan cookies
- select FR language
- add a custom cookie
- set Function to "stocker un identifiant utilisateur unique"
- set Retention to "365 jours"
- set Objective to "Fonctionnel"
- save this cookie
- select EN language
- on the same cookie
- set Function to "store a unique user ID"
- set Retention to "365 days"
- set Objective to "Functional"
- save this cookie
- select FR language
- on the same cookie, Function has been changed to "store a unique user ID"

In database, we can see that all `cookieFunction` column for the same cookie name has been updated.

As a side note, this may happen when we uncheck the "Synchronize with cookiedatabase.org" box on a specific cookie, but it' even more difficult to explain: it's seems to change the `retention` data too...

**Comment by rlankhorst** [comment]
@pierrotevrard-idp, 

I see indeed that the cookieFunction and collectedPersonalData indeed is synced across different languages. This should not be the case. 

I will create a patch for this, thanks.

**Comment by pierrotevrard-idp** [comment]
I rename the ticket to reflect the final issue :)

Thanks a lot

**Comment by rlankhorst** [comment]
This branche should resolve it, we'll be testing it as well. 

https://github.com/rlankhorst/complianz-gdpr/compare/copying-cookiefunction-and-personaldata

**Comment by pierrotevrard-idp** [comment]
Nice.
Gonna have a look on that soon
