### ISSUE TITLE
HTML entities in rendered cookies scripts

### ISSUE THREAD

**Issue by pierrotevrard-idp** [rlankhorst/complianz-gdpr#260]
I've found a issue when I set up a custom script under _Integrations > Scripts center_.

The code I try to input is like:

```
var __sf_config = {
    customer_id: 00000,
    host: 'mails.anonymous.com',
    ip_privacy: 0,
    subsite: 'xwflsd-89kjgl-6789fjjgf',
    __img_path: "/web-next.gif?"
};
var e, t;
var n = 10;
var r = 0;
e = document.createElement("script");
e.type = "text/javascript";
e.async = true;
e.src = "//" + __sf_config.host + "/js/frs-next.js";
t = document.getElementsByTagName("script")[0];
t.parentNode.insertBefore(e, t);
var i = function() {
    if (r < n) {
        r++;
        if (typeof frt !== "undefined") {
            frt(__sf_config);
        } else {
            setTimeout(function() {
                i();
            }, 500);
        }
    }
};
i();
```

When I save settings, the script is HTML encoded in database (option: `complianz_options_wizard`), like so:

```
(...)
s:14:"cookie_scripts";s:...:"var __sf_config = { customer_id: 00000, host: 'mails.anonymous.com', ip_privacy: 0, subsite: 'xwflsd-89kjgl-6789fjjgf', __img_path: "/web-next.gif?" }; var e, t; var n = 10; var r = 0; e = document.createElement("script"); e.type = "text/javascript"; e.async = true; e.src = "//" + __sf_config.host + "/js/frs-next.js"; t = document.getElementsByTagName("script")[0]; t.parentNode.insertBefore(e, t); var i = function() { if (r &lt; n) { r++; if (typeof frt !== &quot;undefined&quot;) { frt(__sf_config); } else { setTimeout(function() { i(); }, 500); } } }; i();";
(...)
```

As we can see, after the `<` character is HTML protected, and everything after it is also HTML protected, and when it's displayed in the `<script>` tag, it does not work and leads to a Javascript Error:

```
<script class="cmplz-native">
				function complianz_enable_cookies() {
					console.log("enabling cookies");
					var __sf_config = { customer_id: 00000, host: 'mails.anonymous.com', ip_privacy: 0, subsite: 'xwflsd-89kjgl-6789fjjgf', __img_path: "/web-next.gif?" }; var e, t; var n = 10; var r = 0; e = document.createElement("script"); e.type = "text/javascript"; e.async = true; e.src = "//" + __sf_config.host + "/js/frs-next.js"; t = document.getElementsByTagName("script")[0]; t.parentNode.insertBefore(e, t); var i = function() { if (r &lt; n) { r++; if (typeof frt !== &quot;undefined&quot;) { frt(__sf_config); } else { setTimeout(function() { i(); }, 500); } } }; i();				}
			</script>
```

I've changed the script to work around this issue, but it could be solved.

**Comment by AertHulsebos** [comment]
Hi @pierrotevrard-idp, (@rlankhorst )

We are ready to merge, did this work for you as well?

regards Aert

**Comment by pierrotevrard-idp** [comment]
@AertHulsebos ,

I'm sorry, I didn't take time to test the branch, but it looks ok. I mean: it's a minor bug (workarounds are possible), I don't see any massive regression, so the changes won't generate any disaster.

May another error will occur when somebody will paste `<script>` tags (they are stripped in current version), but the documentation claims that the field should contain only Javascript, so the error will belong to user :)

I suggest to accept the changes, and I will test it on my next iteration on Complianz GDPR implementation, with pleasure.

Thanks for your attention
