### ISSUE TITLE
Adding support for 3rd party plugins 

### ISSUE THREAD

**Issue by orjhor** [rlankhorst/complianz-gdpr#265]
Hi,
According to the [documentation](https://complianz.io/developers-guide-for-third-party-integrations/), I should be able to make my plugin show up in Complianz -> Integrations -> Plugins. However, it does not show up. When looking into complianz-gdpr\integrations\fields.php it seems the plugin requires the plugin to be located within the Complianz plugin path - is this correct? (see code from fields.php below).
If yes, it seems a bit hacky to add my own .php files to the integrations/plugins/ directory?

```
		if ( file_exists( cmplz_path . "integrations/plugins/$plugin.php" ) ) {

*snip*
		}
```

Thanks in advance!

**Comment by rlankhorst** [comment]
Hi @orjhor, 

Thanks for reporting!

You're right, there is a bug here. It is meant to be overridable with a filter, like in the integrations.php file (where the file is actually loaded), with the 'cmplz_integration_path' filter. 

I've just patched it, and we will ship it with the next update. probably in one or two weeks. 

Let me know if this works for you!
