### ISSUE TITLE
Forces my website to become "full width"

### ISSUE THREAD

**Issue by dpetya** [rlankhorst/complianz-gdpr#7]
Hi,
Great plugin overall, although I have one small issue:
Once I enable the plugin my site becomes full width.
When I disable the plugin it becomes boxed again.

For reference: www.depantyshop.nl
Maybe I am doing something wrong... maybe it is a bug.

**Comment by rlankhorst** [comment]
Hi, 

Thanks for your message. It's hard to see what is causing this without being able to activate/deactivate. Can you contact me on info@complianz.io? If I can get wp admin access, I can compare the deactivated state with the activated state.

**Comment by dpetya** [comment]
Thanks for a quick reply, I have mailed you the login.
